### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by pckroon** [stevengj/nlopt#130]
Hi,

I saw you made a new release versioned as 2.4.2. However, a version 2.4.2 has also been available from http://ab-initio.mit.edu/wiki/index.php/NLopt#Download_and_installation for quite some time. Are the versioning schemes between the distribution channels the same?

Cheers,
Peter

**Comment by stevengj** [comment]
It's not actually a "new" release, it's just moving the hosting for the 2.4.2 release here, in preparation for moving everything from ab-initio to github.  i.e. it's the same as 2.4.2 on ab-initio, with the same tarball attached to the release.

(In particular, this was necessary for JuliaOpt/NLopt.jl#82 because MIT's servers apparently started blocking hosting of DLL binaries.)

**Comment by pckroon** [comment]
Thanks. I missed the line that says "91 commits to master since this release". 

Keep up the good work :)
