### ISSUE TITLE
Parallel Optimization

### ISSUE THREAD

**Issue by jbehura** [stevengj/nlopt#173]
Hi,
I could not locate any reference to parallel computation of objective functions in the documentation. Are all the optimization codes serial?
Thanks,
Jyoti

**Comment by jschueller** [comment]
Funny I had this discussion recently.
The callback to interface the objective function operates on one point at a time for now, but maybe a new callback that operates on several points could take advantage of some algorithms, maybe the evolutionary ones, but I've not looked it, can you think of one ?

**Comment by jbehura** [comment]
Most of the global optimization algorithms should be good candidates...and yes evolutionary algorithms should be great candidates.
I believe there are two ways of doing it --
1. Parallelize the computation of the objective function for one point...that way one can make it algorithm independent
2. Parallelize the computation of objective functions for multiple points...this will be algorithm dependent

**Comment by jschueller** [comment]
1. this would not be the responsibility of nlopt, this can already be done on the user side to
2. The way I see it Nlopt cannot be responsible of the parallelization in itself but provide input points by bulk, then it's the user fonction to parallelize the evaluation of the multiple points and return the result to nlopt.

**Comment by jbehura** [comment]
1. Agreed. In the first case, the user should parallelize each function evaluation.
2. In the 2nd case, however, wherever multiple independent function calls are possible, modifications to NLOPT will significantly add to the efficiency of the algorithms.

**Comment by jschueller** [comment]
2. I'm not saying that parallelization is not possible. I'm just saying NLopt cannot assume thread-safety of the function, that's why I think this should be delegated to the user callback on multiple points.

**Comment by scottfharvey-cm** [comment]
Hi! I was wondering if there is any update on this topic. I have the ability to calculate the objective function for my application in batches of 20 (using cuda), but unfortunately have not figured out how to leverage this parallel benefit for optimization. I'm currently using an "LN" method, but would be ok using a "GN" method if it leveraged the 20x speedup. Ideal interface would be 20 points to calculate, then the next 20 points to calculate based on the results from the first 20 etc.. Any help would be greatly appreciated or if there is another library to try!

**Comment by jschueller** [comment]
@scottfharvey-cm I think no one is working on it, else I think pagmo does parallel optimization.

**Comment by ismet-dagli** [comment]
There is still no update, right?
@jschueller

**Comment by jschueller** [comment]
nope

**Comment by jschueller** [comment]
try pagmo

**Comment by gitouni** [comment]
> 1. this would not be the responsibility of nlopt, this can already be done on the user side to
> 2. The way I see it Nlopt cannot be responsible of the parallelization in itself but provide input points by bulk, then it's the user fonction to parallelize the evaluation of the multiple points and return the result to nlopt.

At least, NLopt should provide an API interface with multiple `x` inputs and multiple `fval` outputs. This case is algorithm-dependant and is also possible to be parallelized by users. Without such an API interface, I cannot figure out in which case can users parallelize the object function computation, sinice it has been wrappered into NLopt itself.

**Comment by jschueller** [comment]
I think it wont be possible to change any of the solvers here to evaluate batches

**Comment by pierre-haessig** [comment]
too bad, but sure most Nlopt algorithms comes from a time when computing was mostly single core. I parallel version of DIRECT would be interesting though...

**Comment by jschueller** [comment]
do you know the pagmo library ?

**Comment by pierre-haessig** [comment]
> do you know the pagmo library ?

Yes, but thanks for the pointer anyway. Very nice lib of global/metaheuristics solvers. 

However, these days I mostly use Nlopt from Julia, and there is no Julia binding of Pagmo for the moment. There exists some pure Julia libraries of metaheuristics, but not as rich as Pagmo. So I'm still interested in Nlopt!

**Comment by jpswensen** [comment]
I have been using nlopt with DirectL on an academic project and it has been fantastic. I think your use of the red-black tree in your from-scratch implementation gives it significant performance increases over the scipy implementation (which it wrapped/derived from the original), mostly in how the space is explored and divided with less overhead.

I had been horsing around with using the ralph-wiggum ML process lately to do some conversion of some of my own old code to Rust and Python, so I decided to try it on converting your from-scratch implementation of the Direct algorithm to a Rust-native implementation with as much concurrency as possible. You can see the result at:

https://github.com/jpswensen/direct-nlopt-rs

I basically told the AI at every step of the conversion to write tests to make sure that the single-threaded/sequential version should be bit-for-bit compatible with the NLOPT implementation. It wrote hundreds of tests along the way comparing almost every individual low-level functionality in the original NLOPT code against the same functionality in this conversion. It took almost 12 hours or running and about $18-20 in premium Github Copilot credit using the Claud Opus 4.6 model. 

The parallel modification, plus your existing tree representations of the hull, have given HUGE performance increases for long-running objective functions. See the PERFORMANCE.md file in my linked repository. i don't know how easy it would be for the original NLOPT code to incorporate this change, as threading can be a little more cumbersome in C/C++. Rust made it super seamless with one is its superpowers, namely seamless concurrency using the Rayon crate. But as a high-level summary, here is how it changed things. One one test I was running, I see all 22 cores of my processor pegged at 100% for hours, and just anecdotally, it finished in about 1/10 the time of using the raw NLOPT Rust crate and the Direct algorithm. So not quite a 22x speedup from having 22 cores, but a non-trivial and highly noticeable improvement.

**Original Approach**

1. Remove the rectangle from the BTreeMap
2. Evaluate f(center - w*THIRD) → immediately check stopping conditions
3. Evaluate f(center + w*THIRD) → immediately check stopping conditions
4. Sort dimensions by min(f+, f-) (the sort depends on the evaluations)
5. Create children and insert them back into the BTreeMap
6. Re-sort/re-key the parent node in the tree

**New Approach**

1. **Collect phase:** For each rectangle selected by the convex hull, compute all candidate points (2×nlongest for Path A, 2 for Path B) without evaluating them.
2. **Evaluate phase:** Batch all candidate points across all selected rectangles and evaluate in parallel with par_iter().
3. **Apply phase:** Feed results back, perform the dimension sort, create children, and insert into the tree sequentially.

I think the end result is that things get explored in a slightly different order, but that they all end up getting explored similarly/identically. And, if you drop back to no-parallel computation, if gives bit-for-bit identical results in the test suite.

If you have no moral objections to using AI on this project, I am more than willing to work with AI to backport the parallelized changes from my Rust adaptation back into the NLOPT codebase and submit a pull request. I would do the same as with my Rust port, namely that if someone doesn't choose parallelization, that it would run the NLOPT Direct algorithm(s) as-is, so that it wouldn't break anyone's existing reliance on the current state of the algorithms.
