### ISSUE TITLE
Fortran API is not exported on Windows

### ISSUE THREAD

**Issue by econwang** [stevengj/nlopt#249]
I compile the lib with cmake and msvc, the resulting lib works well when call from a C program, but can not call from a fortran program, seems that it does not export fortran api `nlo_*`.

**Comment by stevengj** [comment]
Yes, it looks like you are right — on Windows, you need this `__declspec(dllexport)` decorator in order to export functions.   For the regular C API, we have an [`NLOPT_EXTERN` macro](https://github.com/stevengj/nlopt/blob/18cadf72cc69334091492b6137a32471e178e2ed/src/api/nlopt.h#L50) that adds this decorator as needed, but we aren't utilizing this in the [Fortran API definitions](https://github.com/stevengj/nlopt/blob/master/src/api/f77funcs.h).
