### ISSUE TITLE
StoGo does not converge against correct result of BoxBetts' problem

### ISSUE THREAD

**Issue by rainman110** [stevengj/nlopt#267]
No matter what max_eval is set, Stogo is taking always 1000 evaluations for the Box & Betts test function.

This can be reproduced using the testopt executable.

**Comment by stevengj** [comment]
It looks like the maxevals check is there (see the calls to `nlopt_stop_evalstime` and `IF_NLOPT_CHECK_EVALS`) but it is commented out with `#ifdef NLOPT_UTIL_H`, which used to be defined at some point but is not defined by the `cmake` scripts.

We should just remove the `#ifdef NLOPT_UTIL_H` checks, which were originally there so that the stogo code could be compiled separately from nlopt if desired.

**Comment by stevengj** [comment]
Oh, no, `NLOPT_UTIL_H` is defined in `nlopt_util.h`, so that's not the problem.

**Comment by stevengj** [comment]
Actually, I can't reproduce your problem.  On my machine, it is using maxevals::
```sh
test/testopt -a 8 -e 100 -o 2
```
stops after 100 evaluations as requested, and `test/testopt -a 8 -e 10000 -o 2` uses 10000 evaluations.  The default in `testopt` is 1000 evaluations.

Maybe you are passing `-e` after `-o` instead of before?

**Comment by rainman110** [comment]
> Maybe you are passing -e after -o instead of before?

This could be an explanation. I experienced the issue when using nlopt as a library though - not only with the test executable.

I am double checking this and let you know then.

**Comment by rainman110** [comment]
Okay, you are right! MaxEval is respected in my code.

__But__: For the BoxBetts problem, StoGo will return
```
   [0.99311, 10.097, 1.005]
```
no matter how many iterations I use. This is, why I had the impression that the iter count was not respected. The correct result would be [1, 10, 1]. At least, this seems to be strange to me.
