### ISSUE TITLE
Hooke-Jeeves algorithm

### ISSUE THREAD

**Issue by sovrasov** [stevengj/nlopt#306]
Hi @stevengj. Are you interested in adding of the Hooke-Jeeves method?
nlopt already contains similar heuristic-based stuff (Nelder-Mead and Sbplx), but still.
One of my colleagues complained that the nlopt's Nelder-Mead is much slower than my implementation of HJ on the 20d generalized Rosenbrock function. I haven't benckmark the methods by myself yet. To do that correctly I'd rather have both the methods implemented in nlopt, so HJ would be a side-product of that comparison.

**Comment by stevengj** [comment]
In general, I'm open to including new algorithms, but I'd typically like to see a reasonable problem where the new algorithm is better than anything current in NLopt, or otherwise adds some feature not available in the existing algorithms.  So it would be good to compare HJ to other derivative-free algorithms in NLopt too.

However, you don't need to implement the method in NLopt to do the comparison.   For optimization methods like this, a good metric is the number of objective-function evaluations required to reach `minimum+ε` for some given `ε` (for test problems with a known minimum).  (In NLopt, use `nlopt_set_stopval`.)   *Not* wall-clock-time.    This makes it possible to compare algorithms independent of language, compiler, etcetera.

(Nelder-Mead itself is mainly in NLopt for comparison purpose, as is Praxis — these are not algorithms I would normally recommend for real problems.)

**Comment by justinmcgrath** [comment]
I have a problem that Hooke-Jeeves method works well with. It's part of a optimization package, but I like the interface of NLopt considerably more. However, I can't find something in NLopt that works as well. What is the comparable algorithm in NLopt? (I'm a biologist and I am not familiar with the options). I'd like to try something from NLopt, and I think it would be simple for me to do a comparison of the number of function calls between NLopt and what I'm using.

Simulated annealing also works well for my problem, but the software I'm using (also different from the Hooke Jeeves software) doesn't have working stopping conditions, so it runs far longer than I need it to. As above, is there a similar algorithm in NLopt? I tried CRS, which seems roughly similar, but it didn't work well.

**Comment by stevengj** [comment]
There are a bunch of global-optimization algorithms described here: https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/

Useful stopping criteria are always a problem for global optimization.
