### ISSUE TITLE
nlopt Optimization with nonlinear inequality COBYLA

### ISSUE THREAD

**Issue by sgherrero** [stevengj/nlopt#443]
I want to minimize a function where the variable must verify some constraints, i.e, min f(x) where h(x)<=0.
My function f(x) cannot be calculated if h(x) >0. 

I have founded that COBYLA tries with some point x_i, i.e, the optimizer call the function f( . ) at x_i and then the constraint h( . ) is called at x_i. 

Is there any way to avoid calling f( . ) at points that does not verify the inequality h( . ) ?
Is there other local derivative-free optimizer that allows nonlinear inequalities with this property?

I have tried to add to my function f( . ) a penalthy term in order to avoid evaluate if h(x) < 0 but it gives convergence problems so I do not know how to solve the fact that my function f needs to be defined only in a more restrictive set.

Thanks.

**Comment by samuelkim314** [comment]
I am also interested in this, but it seems that NLopt always evaluated the objective function before the constraint in order to determine the next optimization step: https://discourse.julialang.org/t/nlopt-same-complex-clalculations-in-objetive-function-and-nonlinear-constraints/41677/6

**Comment by stevengj** [comment]
No, none of the NLopt algorithms guarantee that they will only evaluate points in the interior of the feasible region (where h < 0).

The only exception is box constraints, which NLopt will always stay inside of.  So if you have a constraint that absolutely must be satisfied at all times (e.g. your objective function is not defined without it), then I would advise re-defining your optimization parameters so that you can express this as a bound/box constraint.
