### ISSUE TITLE
Implement Cyclic Coordinate Descent

### ISSUE THREAD

**Issue by config-i1** [stevengj/nlopt#498]
Hi,

I'm one of users of your library in R. Several of my packages use your function. It works very well for the majority of cases, but I've read that for some of problems I am facing, Cyclic Coordinate Descent is supposed to do a better job. Here is one of the papers on the algorithm: https://home.ttic.edu/~tewari/research/saha10finite#:~:text=Cyclic%20coordinate%20descent%20is%20a,l1%20regularized%20smooth%20optimization%20problems. I've tried implementing it myself in R, but it is slow (because R is slow) and is not practical. Have you considered implementing it or something similar in the nlopt library?
 
By the way, thank you very much for all the work you have done with the nlopt! It's a great library!

**Comment by stevengj** [comment]
That's not an algorithm it looks like I would be interested in implementing — to be honest, like all coordinate-descent algorithms it sounds like a terrible algorithm to me.

The problem is that, by optimizing one coordinate at a time, you inevitably require a number of function and/or gradient evaluations proportional the dimension `d` of the parameter space.   This defeats the whole point of using gradient-based optimization, because it won't scale to huge numbers of parameters.  (e.g. if you have 1000 variables — a *small* number by modern standards — it will take 1000 function evaluations just to complete *one* outer iteration.  Now imagine you have 10^6 parameters.)

**Comment by config-i1** [comment]
Fair enough. I was more interested in it because it does not require gradient (as far as I understand), and I have such tasks. It is told to perform very well for estimation of parameters of LASSO regression (e.g. Tibshirani, Hastie et al., glmnet authors use it in their package). I currently use your SBPLX in my package, but it converges to the optimal value too slowly and requires too many iterations to make it practical. So, I'm looking at the alternatives, and this seemed to be one of them. Anyway, thanks for the response, I'll think what to do with that...

**Comment by stevengj** [comment]
You can do LASSO regression with gradient-based methods by transforming it into an NLP via an epigraph formulation, which gets rid of the nondifferentiability.

**Comment by config-i1** [comment]
That's a good idea, thanks!
