### ISSUE TITLE
Optimization algorithm step size

### ISSUE THREAD

**Issue by Koris** [stevengj/nlopt#65]
I have noticed that the absolute value of the goal function/gradient greatly influences the outcome of the optimization problem. The lower the absolute value, the worse the results of the optimization.

For example, if I scale both objective function and gradient down by a factor 1e-5, using the test problem (http://ab-initio.mit.edu/wiki/index.php/NLopt_Tutorial#Example_in_Python) the results are worse than the original problem. I've tested this with both MMA and SLSQP.

On the other hand, for MMA, the step size also seems to be limited to 0.45 for optimization problems with box constraints (variables bounded 0 <= variable <= 1). Is this behaviour intended?

**Comment by stevengj** [comment]
Unfortunately, a lot of optimization algorithms, probably most of them, ultimately depend on the overall scale of `f(x)` and/or `x`.  I wish that this weren't so.  But many of the algorithms have "dimensionful" constants inside them, e.g. "magic numbers" that set upper/lower bounds on step sizes and things like that.  Because of that, it's usually a good idea to scale your problem so that `f` and `x` are of order unity.

Yes, for MMA the initial [trust region](https://en.wikipedia.org/wiki/Trust_region) size is about half the diameter of the domain, which limits the initial step.

**Comment by Koris** [comment]
Okay, thank you for the clarification.

Can the trust region size for MMA be influenced by this single line?
https://github.com/stevengj/nlopt/blob/5af26227f380e45482fb8ce076d91c3b4c7d2125/mma/mma.c#L202

**Comment by stevengj** [comment]
@Koris, yes, that line sets the initial trust-region size.   (On subsequent steps the trust region can grow or shrink depending on the iterates.)

**Comment by Koris** [comment]
Great, I will do some experiments with it!
